[package]
name = "dioxus-native"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["accessibility", "hot-reload", "menu", "tracing"]
accessibility = ["blitz-shell/accessibility"]
menu = ["blitz-shell/menu"]
tracing = ["dep:tracing", "blitz-shell/tracing"]
hot-reload = ["dep:dioxus-cli-config", "dep:dioxus-devtools"]

[dependencies]
# Blitz dependencies
blitz-traits = { path = "../../../blitz/packages/blitz-traits" }
blitz-dom = { path = "../../../blitz/packages/blitz-dom" }
blitz-shell = { path = "../../../blitz/packages/blitz-shell" }
blitz-net = { path = "../../../blitz/packages/blitz-net" }
blitz-renderer-vello = { path = "../../../blitz/packages/blitz-renderer-vello" }

# DioxusLabs dependencies
dioxus-core = { workspace = true }
dioxus-html = { workspace = true }
dioxus-cli-config = { workspace = true, optional = true }
dioxus-devtools = { workspace = true, optional = true }

# Windowing & Input
winit = { version = "0.30.2", features = ["rwh_06"] }
keyboard-types = { version = "0.7", default-features = false }

# IO & Networking
tokio = { version = "1.25", features = ["full"] }

# Other dependencies
tracing = { workspace = true, optional = true }
rustc-hash = { workspace = true }
futures-util = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
